---

services:
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    hostname: sabnzbd
    ports:
      - "9000:8080"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=000
      - TZ=America/Chicago
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - /AppData/sabnzbd/config:/config
      - /AppData/sabnzbd/backup:/data/backup
      - /mnt/pve/downloads:/data/downloads
    restart: unless-stopped
    networks:
      - arrs

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    hostname: prowlarr
    ports:
      - "9001:9696"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=000
      - TZ=America/Chicago
    volumes:
      - /AppData/prowlarr/config:/config
      - /AppData/prowlarr/backup:/data/backup
      - /mnt/pve/downloads:/data/downloads
    restart: unless-stopped
    networks:
      - arrs

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    hostname: radarr
    ports:
      - "9002:7878"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=000
      - TZ=America/Chicago
    volumes:
      - /AppData/radarr/config:/config
      - /AppData/radarr/backup:/data/backup
      - /mnt/pve/media:/data
      - /mnt/pve/downloads:/data/downloads
    restart: unless-stopped
    networks:
      - arrs

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    hostname: sonarr
    ports:
      - "9003:8989"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=000
      - TZ=America/Chicago
    volumes:
      - /AppData/sonarr/config:/config
      - /AppData/sonarr/backup:/data/backup
      - /mnt/pve/media:/data
      - /mnt/pve/downloads:/data/downloads
    restart: unless-stopped
    networks:
      - arrs

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr:latest
    ports:
      - "5055:5055"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=000
      - TZ=America/Chicago
    volumes:
      - /AppData/overseerr/config:/config
    restart: unless-stopped

  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli:latest
    ports:
      - "8181:8181"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORTS=8181/tcp,8181/udp
    volumes:
      - /AppData/tautulli/config:/config
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  arrs:
    driver: bridge
