version: "3.9"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - /opt/arr-stack/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - arr-net

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - /opt/arr-stack/config/sonarr:/config
      - /data/media:/data/media			# nfs -DataVault bind
      - /data/downloads:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - prowlarr
    networks:
      - arr-net

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - /opt/arr-stack/config/radarr:/config
      - /data/media:/data/media			# nfs -DataVault bind
      - /data/downloads:/data/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
    networks:
      - arr-net

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - /opt/arr-stack/config/sabnzbd:/config
      - /data/downloads:/data/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - arr-net

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Chicago
      - UMASK=000
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/arr-stack/config/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    networks:
      - arr-net

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "1000:1000"
    ports:
      - 8081:80
    volumes:
      - /data:/srv
      # Just mount the DB file specifically
      - /opt/arr-stack/config/filebrowser/filebrowser.db:/database.db
    # Point the app specifically to that file
    command: ["--database", "/database.db"]
    restart: unless-stopped
    networks:
      - arr-net

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK=000
    volumes:
      - /opt/arr-stack/config/lidarr:/config
      - /data/media/music:/data/music			# nfs -DataVault bind
      - /data/downloads:/data/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

slskd:
    image: slskd/slskd:latest
    container_name: slskd
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SHARED_DIR=/music
    # Ports are usually unnecessary with macvlan as the container 
    # gets its own IP, but kept here for reference.
    volumes:
      - /opt/arr-stack/config/slskd:/app
      - /data/media/music:/music
      - /data/downloads/complete/libarr:/data/downloads
    shares:
      directories:
        - /music
    user: "1000:1000"
    restart: unless-stopped
    networks:
      external_net:
        ipv4_address: 192.168.4.110

networks:
  external_net:
    driver: macvlan
    driver_opts:
      parent: eth1  # Links to your eth1 interface
    ipam:
      config:
        - subnet: 192.168.4.0/24    # Change this to match your actual network CIDR
          gateway: 192.168.4.1     # Change this to your router's IP

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - arr-net
      
networks:
  arr-net:
    driver: bridge
